#!/usr/bin/env python3

import argparse

from splatplost.generate_route import generate_route_file
from splatplost.version import __version__


def main(input_file, output):
    generate_route_file(input_file, output)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
            description='Generate instructions for plotting.'
            )
    parser.add_argument("-o", "--output", required=True,
                        dest="output", help="Specify output instruct filename."
                        )
    parser.add_argument("-i", "--input", required=True,
                        dest="input", help="Specify input picture."
                        )
    parser.add_argument("--verbose", action="store_true")
    parser.add_argument("-V", "--version", action="version", version='%(prog)s {version}'.format(version=__version__))
    args = parser.parse_args()
    main(args.input, args.output)
