# Form implementation generated from reading ui file 'connect_to_switch.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
from pathlib import Path

from PyQt6 import uic

file_path: Path = Path(__file__).parent / "connect_to_switch.ui"

Form_ConnectToSwitch, Dialog_ConnectToSwitch = uic.loadUiType(str(file_path))

