# Form implementation generated from reading ui file 'plotter.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
from pathlib import Path

from PyQt6 import uic

file_path = Path(__file__).parent / "plotter.ui"

Form_plotter, Dialog_plotter = uic.loadUiType(str(file_path))
